#!/usr/bin/env bash
# provision-member.sh -- FR-14 / OQ-09: admin-provisioned members.
#
# Gitea is the source of truth for team membership. This script:
#   1. creates a Gitea user (temp password + must-change-password),
#   2. adds them to an openchoreo org team (default: members, created on
#      first use with write permission),
#   3. regenerates backstage/examples/org.yaml FROM live Gitea state, so the
#      catalog's User/Group entities are generated, never hand-edited.
#
# Subcommands:
#   provision-member.sh create <username> <email> [full name] [--team <slug>]
#       Creates the user (idempotent: an existing user is left untouched and
#       no password is printed), ensures the team, adds the membership, then
#       syncs org.yaml. The temp password is printed exactly once on stdout.
#   provision-member.sh sync
#       Regenerates backstage/examples/org.yaml from live Gitea state only.
#
# Idempotent throughout: re-running any subcommand converges to the same
# state. org.yaml is rewritten atomically on every sync.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ORG_YAML="${ROOT}/backstage/examples/org.yaml"
GITEA_URL="${GITEA_URL:-http://localhost:3333}"
ORG="${GITEA_ORG:-openchoreo}"
ADMIN_USER="${GITEA_ADMIN_USER:-gitea_admin}"
ADMIN_PASS="$(cat ~/.rational-reserve/m1-gitea-admin-password)"
DEFAULT_TEAM=members

SYNC_TMP=""
cleanup_tmp() {
    [ -n "$SYNC_TMP" ] && rm -f "$SYNC_TMP"
    return 0
}
trap cleanup_tmp EXIT

api() {
    local method=$1; shift
    local path=$1; shift
    curl -fsS -u "${ADMIN_USER}:${ADMIN_PASS}" \
        -X "$method" "${GITEA_URL}${path}" \
        -H 'Content-Type: application/json' "$@"
}

# JSON-quote a string; JSON string syntax is valid YAML 1.2 double-quoted
# scalar syntax, so this is safe emission for free-text fields.
yq_str() {
    jq -cn --arg v "$1" '$v'
}

# Lowercase a Gitea team name into a Backstage-safe group name.
slug() {
    printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-'
}

require_safe_name() {
    # Entity names and logins must stay URL/YAML-safe.
    if ! printf '%s' "$1" | grep -qE '^[a-zA-Z0-9._-]+$'; then
        echo "ERROR: unsafe name '$1' (allowed: [a-zA-Z0-9._-])" >&2
        exit 1
    fi
}

team_ids() {
    api GET "/api/v1/orgs/${ORG}/teams" | jq -r '.[].id'
}

team_name() {
    api GET "/api/v1/teams/$1" | jq -r '.name'
}

team_members() {
    api GET "/api/v1/teams/$1/members" | jq -r '.[].login' | sort
}

org_members() {
    api GET "/api/v1/orgs/${ORG}/members" | jq -r '.[].login' | sort
}

# Echoes the slugs of every org team the given login belongs to (sorted).
teams_of_user() {
    local login=$1 tid
    while read -r tid; do
        [ -z "$tid" ] && continue
        if team_members "$tid" | grep -qx "$login"; then
            slug "$(team_name "$tid")"
        fi
    done < <(team_ids) | sort -u
}

ensure_team() {
    # $1 = team slug. Creates the team with write permission if absent.
    # Echoes the team id.
    local slug_name=$1 existing
    require_safe_name "$slug_name"
    existing=$(api GET "/api/v1/orgs/${ORG}/teams" \
        | jq -r --arg s "$slug_name" \
            '.[] | select((.name | ascii_downcase) == $s) | .id')
    if [ -n "$existing" ]; then
        printf '%s\n' "$existing"
        return
    fi
    api POST "/api/v1/orgs/${ORG}/teams" -d "{
      \"name\": $(yq_str "$slug_name"),
      \"description\": \"Developer members of the ${ORG} org (provision-member.sh)\",
      \"permission\": \"write\",
      \"includes_all_repositories\": true,
      \"units\": [\"repo.code\", \"repo.issues\", \"repo.pulls\", \"repo.actions\", \"repo.packages\", \"repo.releases\"]
    }" | jq -r '.id'
}

add_to_team() {
    # $1 = team id, $2 = username. PUT membership is idempotent.
    api PUT "/api/v1/teams/$1/members/$2" -d '' >/dev/null
    echo "added $2 to team id $1"
}

sync_org_yaml() {
    # Regenerate backstage/examples/org.yaml from live Gitea state:
    # static portal-local guest identities, then one User per org member,
    # one Group for the org, and one Group per org team.
    local tmp login tid tslug tname tdesc full_name email member_of sep first
    local members_json member_count

    # Fail fast BEFORE writing: a dead Gitea or bad credentials must never
    # produce an empty generated file (process substitutions in the loops
    # below do not propagate failures under set -e).
    api GET "/api/v1/orgs/${ORG}" >/dev/null
    member_count=$(org_members | grep -c . || true)
    if [ "$member_count" -eq 0 ]; then
        echo "ERROR: Gitea org ${ORG} returned zero members; refusing to regenerate ${ORG_YAML}" >&2
        exit 1
    fi

    tmp=$(mktemp "${ORG_YAML}.XXXXXX")
    SYNC_TMP="$tmp"

    {
        cat <<'HEADER'
# GENERATED by scripts/provision-member.sh from live Gitea state (FR-14/OQ-09).
# Do not hand-edit. Regenerate with: scripts/provision-member.sh sync
# Gitea is the source of truth for users, teams, and membership. The guest
# identities below are portal-local (the guest auth provider) and have no
# Gitea counterpart; they are the only static section of this file.
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
HEADER

        # Users: one per org member, in sorted login order.
        while read -r login; do
            [ -z "$login" ] && continue
            require_safe_name "$login"
            members_json=$(api GET "/api/v1/users/${login}")
            full_name=$(printf '%s' "$members_json" | jq -r '.full_name // ""')
            email=$(printf '%s' "$members_json" | jq -r '.email // ""')
            member_of="\"$ORG\""
            while read -r tslug; do
                [ -z "$tslug" ] && continue
                member_of="${member_of}, \"$tslug\""
            done < <(teams_of_user "$login")
            echo "---"
            echo "apiVersion: backstage.io/v1alpha1"
            echo "kind: User"
            echo "metadata:"
            echo "  name: ${login}"
            echo "  annotations:"
            echo "    gitea.com/user: ${login}"
            echo "spec:"
            echo "  profile:"
            [ -n "$full_name" ] && echo "    displayName: $(yq_str "$full_name")"
            [ -n "$email" ] && echo "    email: $(yq_str "$email")"
            echo "  memberOf: [${member_of}]"
        done < <(org_members)

        # Org group: every org member.
        tdesc=$(api GET "/api/v1/orgs/${ORG}" | jq -r '.description // ""')
        [ -z "$tdesc" ] && tdesc="OpenChoreo platform team"
        echo "---"
        echo "apiVersion: backstage.io/v1alpha1"
        echo "kind: Group"
        echo "metadata:"
        echo "  name: ${ORG}"
        echo "  description: $(yq_str "$tdesc")"
        echo "spec:"
        echo "  type: team"
        echo "  children: []"
        printf '  members: ['
        sep=""
        while read -r login; do
            [ -z "$login" ] && continue
            printf '%s%s' "$sep" "$login"
            sep=", "
        done < <(org_members)
        printf ']\n'

        # One group per org team.
        while read -r tid; do
            [ -z "$tid" ] && continue
            tname=$(team_name "$tid")
            tslug=$(slug "$tname")
            require_safe_name "$tslug"
            tdesc=$(api GET "/api/v1/teams/${tid}" | jq -r '.description // ""')
            [ -z "$tdesc" ] && tdesc="Gitea team ${tname} of org ${ORG}"
            echo "---"
            echo "apiVersion: backstage.io/v1alpha1"
            echo "kind: Group"
            echo "metadata:"
            echo "  name: ${tslug}"
            echo "  description: $(yq_str "$tdesc")"
            echo "spec:"
            echo "  type: team"
            echo "  children: []"
            printf '  members: ['
            sep=""
            first=1
            while read -r login; do
                [ -z "$login" ] && continue
                printf '%s%s' "$sep" "$login"
                sep=", "
            done < <(team_members "$tid")
            printf ']\n'
        done < <(team_ids)
    } >"$tmp"

    mv "$tmp" "$ORG_YAML"
    SYNC_TMP=""
    echo "regenerated ${ORG_YAML} from Gitea org ${ORG} state"
}

cmd=${1:-}
case "$cmd" in
    create)
        username=${2:-}
        email=${3:-}
        if [ -z "$username" ] || [ -z "$email" ]; then
            echo "usage: $0 create <username> <email> [full name] [--team <slug>]" >&2
            exit 64
        fi
        require_safe_name "$username"
        shift 3
        full_name=""
        if [ $# -gt 0 ] && [ "$1" != "--team" ]; then
            full_name=$1
            shift
        fi
        team_slug=$DEFAULT_TEAM
        while [ $# -gt 0 ]; do
            case "$1" in
                --team)
                    [ $# -ge 2 ] || { echo "$0: --team needs a value" >&2; exit 64; }
                    team_slug=$2
                    shift 2
                    ;;
                *)
                    echo "unknown argument: $1" >&2
                    exit 64
                    ;;
            esac
        done

        if api GET "/api/v1/users/${username}" >/dev/null 2>&1; then
            echo "user ${username} already exists; leaving account and password unchanged"
        else
            temp_password=$(openssl rand -hex 12)
            api POST /api/v1/admin/users -d "{
              \"username\": $(yq_str "$username"),
              \"login_name\": $(yq_str "$username"),
              \"email\": $(yq_str "$email"),
              \"full_name\": $(yq_str "$full_name"),
              \"password\": $(yq_str "$temp_password"),
              \"must_change_password\": true,
              \"send_notify\": false,
              \"visibility\": \"public\"
            }" >/dev/null
            echo "created Gitea user ${username} (must_change_password=true)"
            echo "TEMPORARY PASSWORD (hand to the member, shown once): ${temp_password}"
        fi

        team_id=$(ensure_team "$team_slug")
        add_to_team "$team_id" "$username"
        sync_org_yaml
        ;;
    sync)
        sync_org_yaml
        ;;
    *)
        echo "usage: $0 {create <username> <email> [full name] [--team <slug>] | sync}" >&2
        exit 64
        ;;
esac
